### ISSUE TITLE
Google Account linking fails with 'Invalid ClientID'

### ISSUE THREAD

**Issue by peterkappelt** [kservices/gBridge#28]
I have tried the above fixes to the docker-compose file and ApplicationServiceProvider file and still having issues with the account linking being redirected to /gapi/auth. Is there something else I have missed. I have had a look in the docker-compose logs for errors but everything appears ok, no fatal errors.

To try and get round the proxy issue I used my Sophos firewall  WAF function, and stopped apache. I can know add account details as page direct is right but on pressing 'Link Accounts' I get a red error box on the web page saying 'request by Googlehome is malformed .... Invalid ClientID provided'. Checked google console and docker-compose file and clientid entry match. Is this another issue.

_Originally posted by @jaseuk73 in https://github.com/kservices/gBridge/issues/17#issuecomment-452737123_

**Comment by peterkappelt** [comment]
The proxy issue will be solved with the update on saturday.

This seems like a different issue. First a simple thing, to make sure there is no misunterstanding: Could you read #26 ? Are you linking the account as described there?

**Comment by jaseuk73** [comment]
thank you for the assistance @peterkappelt . I mis-read the docs and thought you linked it from web page, my apologies.
 I have now used the home app and selected my [test] app and tried linking, not getting any errors on web page but when I press 'link account', details in the email and password boxes clear and nothing else happens. Checked local bridge web page and no account link shown. I will check my logs to see if anything shows up. I may return the vm to base condition and create new docker-compose after Saturday to remove any possible issues using Sophos as pseudo proxy. I will post any relevant info from logs if found.

**Comment by shoaibali** [comment]
@peterkappelt I have been bashing my head against this problem for the past couple of hours. I have a self-hosted instance of it running on docker. I folllowed the documention very closely. I am not sure what I am missing. 

I am fairly certain there is a bug some where. The form that is rendered for linking account has no client_id value nor it has any other values. its completely empty.

```
<form class="form-horizontal" method="POST" accept-charset="UTF-8" action="http://192.168.1.107:8888/gapi/auth">
                    <input type="hidden" name="_token" value="0qRLql8b2EqPjDeWOSffUh0xfoH3si9PPoYiPl4d">
                    <input type="hidden" name="client_id" value="">
                    <input type="hidden" name="response_type" value="">
                    <input type="hidden" name="redirect_uri" value="">
                    <input type="hidden" name="state" value="">
                    <div class="card-content black-text">
                        <p><span class="card-title">Link Accounts</span></p>
                                                    
                            <b>Hi shoaib@webstrike.co.nz!</b>
                            <p>Click the button below to link your gBridge account to Google.</p>
                                            </div>
                    <div class="card-action">
                        <button style="width: 100%;" class="btn waves-effect blue" type="submit">
                                                        <i class="material-icons left">navigate_next</i>Confirm Linking
                                                    </button>
                    </div>
                </form>
```

I am hosting it on 192.168.1.107:8888, I even tried hacking the values in but eventually it complains about invalid RedirectURI and rightly so. Since I have a FQDN configured within app settings on Google. 

I even tried removing all security barriers put by mod_proxy. Exposing the entire gBridge to the internet. But then, authentication stops working. 

Lastly, I cant even see the  project I have registered within Google Actions. Do I have to complete the entire process of deploying to production before I see it? Even that part of Google Actions is broken. 

```
GoogleFulfillment 'GoogleFulfillmentName{name=actions.fulfillment.devices, template=false, explicitTemplateProject=false}' is not supported
```

Here is my docker compose file. 

```
version: '3'
networks:
   backend:
      driver: bridge
   web_frontend:
      driver: bridge
services:
   web:
      image: 'pkap/gbridge-web:latest'
      restart: always
      ports:
         - '8888:80'
      environment:
         APP_ENV: production
         APP_KEY: 'base64:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx='
         APP_DEBUG: 'false'
         APP_LOG_LEVEL: warning
         APP_URL: 'http://localhost'
         DB_CONNECTION: mysql
         DB_HOST: database
         DB_PORT: 3306
         DB_DATABASE: gbridge_db
         DB_USERNAME: gbridge_db
         DB_PASSWORD: ntbs0cja1dc
         BROADCAST_DRIVER: log
         CACHE_DRIVER: file
         SESSION_DRIVER: file
         SESSION_LIFETIME: 120
         QUEUE_DRIVER: sync
         REDIS_HOST: cache
         REDIS_PASSWORD: 'null'
         REDIS_PORT: '6379'
         MAIL_DRIVER: smtp
         MAIL_HOST: ERROR
         MAIL_PORT: ERROR
         MAIL_USERNAME: ERROR
         MAIL_PASSWORD: ERROR
         MAIL_ENCRYPTION: ERROR
         GOOGLE_CLIENTID: adc80562f8xxxxxxxxxxxxxx0a6551
         GOOGLE_PROJECTID: ' shoaib-s-home-control'
      links:
         - database
         - cache
      depends_on:
         - database
         - cache
      networks:
         - web_frontend
         - backend
   redis-worker:
      image: 'pkap/gbridge-redis-worker:latest'
      restart: always
      environment:
         GBRIDGE_REDISWORKER_REDIS: 'redis://cache:6379'
         GBRIDGE_REDISWORKER_MQTT: 'mqtt://localhost:1883'
         GBRIDGE_REDISWORKER_MQTTUSER: shoaib
         GBRIDGE_REDISWORKER_MQTTPASSWORD: xxxxxxxx
         GBRIDGE_REDISWORKER_HOMEGRAPHKEY: AIzaSyAm1byUyxxxxxxxxxxxxx0N7RTcfVJdsI
      networks:
         - backend
      links:
         - cache
      depends_on:
         - cache
   database:
      image: 'mysql:5'
      restart: always
      environment:
         MYSQL_RANDOM_ROOT_PASSWORD: 'true'
         MYSQL_DATABASE: gbridge_db
         MYSQL_USER: gbridge_db
         MYSQL_PASSWORD: nxxxxxja1xx
      expose:
         - '3306'
      networks:
         - backend
   cache:
      image: 'redis:4'
      restart: always
      expose:
         - '6379'
      networks:
         - backend

```
